# Generated by Django 4.1 on 2023-12-27 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
