# Generated by Django 4.1 on 2023-12-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tittle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
