# Generated by Django 4.1 on 2023-12-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
