# Generated by Django 4.1 on 2024-01-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='staticsBlog/covers/%Y/%m/%d/'),
        ),
    ]
